{{- define "helm-library.azure-identity-binding.tpl" -}}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ .Chart.Name }}-identity-binding
  labels: {{- include "helm-library.labels" . | nindent 4 }}
spec:
  azureIdentity: {{ .Chart.Name }}-identity
  selector: {{ .Chart.Name }}-identity-selector
{{- end -}}
{{- define "helm-library.azure-identity-binding" -}}
{{- include "helm-library.util.merge" (append . "helm-library.azure-identity-binding.tpl") -}}
{{- end -}}
