{{- define "helm-library.azure-identity.tpl" -}}
{{- $requiredMsg := include "helm-library.default-check-required-msg" . -}}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ .Chart.Name }}-identity
  labels: {{- include "helm-library.labels" . | nindent 4 }}
  annotations:
    aadpodidentity.k8s.io/Behavior: namespaced
spec:
  type: 0
  resourceID: {{ required (printf $requiredMsg "azureIdentity.resourceID") .Values.azureIdentity.resourceID | quote }}
  clientID: {{ required (printf $requiredMsg "azureIdentity.clientID") .Values.azureIdentity.clientID | quote }}
{{- end -}}
{{- define "helm-library.azure-identity" -}}
{{- include "helm-library.util.merge" (append . "helm-library.azure-identity.tpl") -}}
{{- end -}}
