{{- define "helm-library.infiscal-secret.tpl" -}}
{{- $requiredMsg := include "helm-library.default-check-required-msg" . -}}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ .Chart.Name | quote }}
  labels:
    {{- include "helm-library.labels" . | nindent 4 }}
spec:
  resyncInterval: {{ .Values.secret.resyncInterval | default 10 }}
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: {{ .Values.secret.projectSlug | default "contabo-k-nii" | quote }}
        envSlug: {{ .Values.secret.envSlug | default "prod" | quote }}
        secretsPath: {{ .Values.secret.secretsPath | default "/" | quote }}
        recursive: {{ .Values.secret.recursive | default true }}
      credentialsRef:
        secretName: {{ .Values.secret.secretName | default "universal-auth-credentials" | quote }}
        secretNamespace: {{ .Values.secret.secretNamespace | default "infiscal" | quote }}
  managedSecretReference:
    secretName: {{ .Chart.Name | quote }}
    secretNamespace: {{ .Release.Namespace | quote }}
    creationPolicy: {{ .Values.secret.creationPolicy | default "Owner" | quote }}
{{- end }}
{{- define "helm-library.infiscal-secret" -}}
{{- include "helm-library.util.merge" (append . "helm-library.infiscal-secret.tpl") -}}
{{- end -}}
