{{- define "helm-library.infiscal-secret.tpl" -}}
{{- $requiredMsg := include "helm-library.default-check-required-msg" . -}}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name }}-infiscal-secret
  labels:
    {{- include "helm-library.labels" . | nindent 4 }}
type: {{ required (printf $requiredMsg "secret.type") .Values.secret.type | quote }}
authentication:
  universalAuth:
    secretsScope:
        projectSlug: {{ .Values.secret.projectSlug | default "Contabo" | quote }}
        envSlug: {{ .Values.secret.envSlug | default "prod" | quote }}
        secretsPath: {{ .Values.secret.secretsPath | default "/" | quote }}
    credentialsRef:
        secretName: {{ .Values.secret.secretName | default "universal-auth-credentials" | quote }}
        secretNamespace: {{ .Values.secret.secretNamespace | default "infiscal" | quote }}
{{- end }}
{{- define "helm-library.infiscal-secret" -}}
{{- include "helm-library.util.merge" (append . "helm-library.secret.tpl") -}}
{{- end -}}
