{{- define "helm-library.postgres-service.tpl" -}}
{{- $requiredMsg := include "helm-library.default-check-required-msg" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ required (printf $requiredMsg "postgres.host") .Values.postgres.host | quote }}
  labels:
    {{- include "helm-library.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ required (printf $requiredMsg "postgres.externalName") .Values.postgres.externalName | quote }}
  ports:
    - name: port
      port: {{ required (printf $requiredMsg "postgres.port") .Values.postgres.port }}
{{- end -}}
{{- define "helm-library.postgres-service" -}}
{{- include "helm-library.util.merge" (append . "helm-library.postgres-service.tpl") -}}
{{- end -}}
