{{- define "helm-library.secret.tpl" -}}
{{- $requiredMsg := include "helm-library.default-check-required-msg" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  labels:
    {{- include "helm-library.labels" . | nindent 4 }}
type: {{ .Values.secret.type | default "Opaque" | quote }}
data: {}
{{- end }}
{{- define "helm-library.secret" -}}
{{- include "helm-library.util.merge" (append . "helm-library.secret.tpl") -}}
{{- end -}}
