{{- define "helm-library.statefulset.tpl" -}}
{{- $requiredMsg := include "helm-library.default-check-required-msg" . -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ required (printf $requiredMsg "name") .Values.name | quote }}
  labels:
    {{- include "helm-library.labels" . | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ required (printf $requiredMsg "deployment.replicas") .Values.deployment.replicas }}
  serviceName: {{ .Values.name }}
  selector:
    matchLabels:
      {{- include "helm-library.selector-labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- if .Values.azureIdentity }}
        aadpodidbinding: {{ required (printf $requiredMsg "name") .Values.name }}-identity-selector
        {{- end }}
        {{- include "helm-library.labels" . | nindent 8 }}
      annotations:
        linkerd.io/inject: enabled
        redeployOnChange: {{ randAlphaNum 5 | quote }}
    spec:
      {{- if .Values.serviceAccount }}
      {{- if .Values.serviceAccount.roleArn }}
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      {{- end }}
      {{- end }}
      {{- if .Values.deployment.imagePullSecret }}
      imagePullSecrets:
      - name: {{ required (printf $requiredMsg "deployment.imagePullSecret") .Values.deployment.imagePullSecret| quote }}
      {{- end }}
      securityContext:
        fsGroup: {{ .Values.deployment.runAsUser | default 1000 }}
        runAsUser: {{ .Values.deployment.runAsUser | default 1000 }}
        runAsNonRoot: {{ .Values.deployment.runAsNonRoot | default true }}
      volumes:
      - name: temp-dir
        emptyDir: {}
      containers:
      -
{{ include "helm-library.container.tpl" . | indent 8 }}
{{- end }}
{{- define "helm-library.statefulset" -}}
{{- include "helm-library.util.merge" (append . "helm-library.statefulset.tpl") -}}
{{- end -}}
